[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
numReplicas = 1
sleepApplication = false
restartPolicyType = "always"

[[deploy.healthcheck]]
httpPath = "/health"
initialDelaySeconds = 60
periodSeconds = 10
timeoutSeconds = 5
failureThreshold = 3

[environments.production]
variables = { USE_TEST_DATA = "true", TEST_DATA_PRESET = "cardiology_phase2", DEBUG = "false", LOG_LEVEL = "INFO" }