name: Test Before Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        cd backend
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run deployment validation
      run: |
        cd backend
        python validate_deployment.py
    
    - name: Run import tests
      run: |
        cd backend
        python -m pytest tests/test_imports.py -v
    
    - name: Run deployment readiness tests
      run: |
        cd backend
        python -m pytest tests/test_deployment_readiness.py -v
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY || 'test-key' }}
        USE_TEST_DATA: 'true'